jobs:
  -
    reduce_sectors:
      reduce:
        -
          sectors: [3]
          r: 6
          s: 2
      select_integrals:
        select_mandatory_list:
          - ["bub00", "integrals"]
      run_initiate: true
      run_triangular: true
      run_back_substitution: true
  -
    kira2math:
      target:
        - ["bub00", "integrals"]
