integralfamilies:
  -
    name: "SR212"
    loop_momenta: ["l1", "l2"]
    top_level_sectors: [31]
    propagators:
      - ["-l1^2", 0]
      - ["-(l1+p)^2", 0]
      - ["-l2^2", 0]
      - ["-(l2+p)^2", 0]
      - ["-(l1+l2+p)^2", 0]
