(* C++ Relation Export: All Results *)
(* Family: bub11, Order: 4, NE: 2, Modulus: 179424673 *)
(* Total configurations: 6, with solution: 6 *)
$AllRelations = {
  <|
    "Family" -> "bub11",
    "Lev" -> 1,
    "Deg" -> 0,
    "NE" -> 2,
    "AnsatzMode" -> "Pyramid",
    "Modulus" -> 179424673,
    "Order" -> 4,
    "StableOrder" -> 0,
    "NumRelations" -> 0,
    "ActiveVars" -> 3,
    "TotalVars" -> 3,
    "Alphas" -> {{0,0}, {0,1}, {1,0}},
    "Betas" -> {{0,0}},
    "Coefficients" -> {
      {0},
      {0},
      {0}
    },
    "IndependentPairs" -> {},
    "HasSolution" -> True,
    "NumVariables" -> 3,
    "NumSolutions" -> 0
  |>,
  <|
    "Family" -> "bub11",
    "Lev" -> 1,
    "Deg" -> 1,
    "NE" -> 2,
    "AnsatzMode" -> "Pyramid",
    "Modulus" -> 179424673,
    "Order" -> 4,
    "StableOrder" -> 0,
    "NumRelations" -> 0,
    "ActiveVars" -> 9,
    "TotalVars" -> 9,
    "Alphas" -> {{0,0}, {0,1}, {1,0}},
    "Betas" -> {{0,0}, {0,1}, {1,0}},
    "Coefficients" -> {
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0}
    },
    "IndependentPairs" -> {},
    "HasSolution" -> True,
    "NumVariables" -> 9,
    "NumSolutions" -> 0
  |>,
  <|
    "Family" -> "bub11",
    "Lev" -> 1,
    "Deg" -> 2,
    "NE" -> 2,
    "AnsatzMode" -> "Pyramid",
    "Modulus" -> 179424673,
    "Order" -> 4,
    "StableOrder" -> 0,
    "NumRelations" -> 0,
    "ActiveVars" -> 18,
    "TotalVars" -> 18,
    "Alphas" -> {{0,0}, {0,1}, {1,0}},
    "Betas" -> {{0,0}, {0,1}, {0,2}, {1,0}, {1,1}, {2,0}},
    "Coefficients" -> {
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0}
    },
    "IndependentPairs" -> {},
    "HasSolution" -> True,
    "NumVariables" -> 18,
    "NumSolutions" -> 0
  |>,
  <|
    "Family" -> "bub11",
    "Lev" -> 2,
    "Deg" -> 0,
    "NE" -> 2,
    "AnsatzMode" -> "Pyramid",
    "Modulus" -> 179424673,
    "Order" -> 4,
    "StableOrder" -> 0,
    "NumRelations" -> 0,
    "ActiveVars" -> 6,
    "TotalVars" -> 6,
    "Alphas" -> {{0,0}, {0,1}, {1,0}, {0,2}, {1,1}, {2,0}},
    "Betas" -> {{0,0}},
    "Coefficients" -> {
      {0},
      {0},
      {0},
      {0},
      {0},
      {0}
    },
    "IndependentPairs" -> {},
    "HasSolution" -> True,
    "NumVariables" -> 6,
    "NumSolutions" -> 0
  |>,
  <|
    "Family" -> "bub11",
    "Lev" -> 2,
    "Deg" -> 1,
    "NE" -> 2,
    "AnsatzMode" -> "Pyramid",
    "Modulus" -> 179424673,
    "Order" -> 4,
    "StableOrder" -> 0,
    "NumRelations" -> 0,
    "ActiveVars" -> 18,
    "TotalVars" -> 18,
    "Alphas" -> {{0,0}, {0,1}, {1,0}, {0,2}, {1,1}, {2,0}},
    "Betas" -> {{0,0}, {0,1}, {1,0}},
    "Coefficients" -> {
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0}
    },
    "IndependentPairs" -> {},
    "HasSolution" -> True,
    "NumVariables" -> 18,
    "NumSolutions" -> 0
  |>,
  <|
    "Family" -> "bub11",
    "Lev" -> 2,
    "Deg" -> 2,
    "NE" -> 2,
    "AnsatzMode" -> "Pyramid",
    "Modulus" -> 179424673,
    "Order" -> 4,
    "StableOrder" -> 1,
    "NumRelations" -> 0,
    "ActiveVars" -> 36,
    "TotalVars" -> 36,
    "Alphas" -> {{0,0}, {0,1}, {1,0}, {0,2}, {1,1}, {2,0}},
    "Betas" -> {{0,0}, {0,1}, {0,2}, {1,0}, {1,1}, {2,0}},
    "Coefficients" -> {
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0},
      {0}
    },
    "IndependentPairs" -> {},
    "HasSolution" -> True,
    "NumVariables" -> 36,
    "NumSolutions" -> 0
  |>
};
